version: '2.1'

services:
  python-simple-http-logger:
    image: kovalewvladimir/python-simple-http-logger
    volumes: 
      - ./server.log:/app/server.log
      - ./logs:/app/logs
    ports:
      - 9000:9000
    restart: always
  web:
    image: dragas/thttpd
    volumes: 
      - ./logs:/var/www/http
    ports: 
      - 9001:80
    restart: always